[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "requests>=2.29.0",
    "urllib3>=1.26.15",
    "progressbar2>=4.2.0",
    "pymisp>=2.4.170.1",
    "PyYAML>=6.0",
    "ruamel-yaml>=0.17.21",
    "termcolor>=2.3.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
