[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "requests>=2.31.0",
    "urllib3>=2.0.4",
    "progressbar2>=4.2.0",
    "pymisp>=2.4.173",
    "PyYAML>=6.0.1",
    "ruamel-yaml>=0.17.32",
    "termcolor>=2.3.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

