
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "requests>=2.31.0",
    "urllib3>=2.0.3",
    "progressbar2>=4.2.0",
    "pymisp>=2.4.172",
    "PyYAML>=6.0",
    "ruamel-yaml>=0.17.32",
    "termcolor>=2.3.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
