[tool]
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[tool.pdm.dev-dependencies]
dev = [
    "coverage~=5.0",
    "yamllint~=1.21",
    "elasticsearch~=7.6",
    "elasticsearch-async~=6.2",
    "pytest~=5.4",
    "colorama",
    "setuptools",
    "stix2",
    "attackcti",
]

[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
requires-python = ">=3.8"
dependencies = [
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
    "requests~=2.25",
    "urllib3~=1.26",
    "progressbar2~=3.47",
    "pymisp~=2.4.123",
    "PyYAML~=5.1",
    "ruamel.yaml",
    "termcolor",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"
